#!/bin/bash

connections=$(nmcli -t --color=no con show --active)

ssid=$(awk -F: '$3 == "802-11-wireless" { print $1 }' <<< "$connections" | head -1)
vpns=$(awk -F: '$3 == "vpn" { print $1 }' <<< "$connections")

ssid=${ssid:-(no wifi)}
vpn=''
if [[ -n vpns ]]; then
	vpn=' (vpn)'
fi

echo "$ssid$vpn"

