#!/bin/sh

SCRIPT_DIR="$HOME/.local/bin"
SCRIPT_FILE="$SCRIPT_DIR/$1"

if [ ! -f "$SCRIPT_FILE" ] ; then
    echo '#!/bin/sh\n' > "$SCRIPT_FILE"
    chmod +x "$SCRIPT_FILE"
    vim "+normal Go" "$SCRIPT_FILE"
else
    vim "$SCRIPT_FILE"
fi
