#!/bin/sh

# https://gist.github.com/Blaradox/030f06d165a82583ae817ee954438f2e

# $ brightnessControl up
# $ brightnessControl down

get_brightness() {
	xbacklight -get | cut -d '.' -f 1
}

send_notification() {
	icon="preferences-system-brightness-lock"
	brightness=$(get_brightness)
	bar=$(seq -s "─" 0 $((brightness / 5)) | sed 's/[0-9]//g')
	dunstify -i "$icon" -r 5555 -u normal "    $bar"
}

case $1 in
	up)
		xbacklight -inc 5
		send_notification
		;;
	down)
		xbacklight -dec 5
		send_notification
		;;
esac
