#!/bin/bash

#https://gitlab.com/impascal/conf-dotfiles/blob/master/scripts/dmenu-usb

getmount() { \
	[ -z "$chosen" ] && exit 1
	mp="$(find $1 | dmenu -i -p "Type in mount point.")"
	[ "$mp" = "" ] && exit 1
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
}

mountusb() { \
	usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
	[ -z $usbdrives ] && notify-send "No USB drives detected" && exit
	chosen="$(echo "$usbdrives" | dmenu -i -p "Mount which drive?" | awk '{print $1}')"
	sudo -A mount "$chosen" && notify-send "USB mounting" "$chosen mounted." && exit 0
	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$2=="part"&&$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not \( -path *%s -prune \) \ \n",$3}')
	getmount "$HOME -maxdepth 5 -type d $alreadymounted"
	partitiontype="$(lsblk -no "fstype" "$chosen")"
	case "$partitiontype" in
		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" 741 "$mp";;
	esac
	notify-send "$chosen mounted to $mp."
}

unmountusb() {
	usbdrives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')
	[ -z $usbdrives ] && notify-send "No USB drives to unmount" && exit
	chosen=$(echo "$usbdrives" | dmenu -p "Unmount which drive?" | awk '{print $1}')
	[ -z "$chosen" ] && exit
	sudo -A umount "$chosen" && notify-send "$chosen unmounted."
}

help_me() {
	echo "Usage: dmenu-usb [OPTION]"
	echo -e "\n-m		mount drives"
	echo "-u		umount drives"
	echo "--help		show this help"
}

case $1 in
	"-m") mountusb ;;
	"-u") unmountusb ;;
	"--help") help_me ;;
esac

