#!/bin/bash
#https://github.com/elken/bin/blob/7cba7d1c1f9d081408e687627e6916f75d4a38c4/dwm-status.sh

normal="\x01"
red="\x05"
yellow="\x06"
green="\x08"
blue="\x07"
rebbg="\x0c"
yellowbg="\x0d"
greenbg="\x0e"
bluebg="\x0f"

getBattery() {
	perc=$(acpi -b | awk '/Battery/ {print $4}' | cut -d% -f1)
	time=$(acpi -b | awk '/Battery/ {print " (" substr($5,1,5)")"}')
	is_charging=$(acpi -a | awk '/Adapter/ {print $3}')

	if [ "${is_charging}" != "on-line" ]; then
		if [ ${perc} -eq "100" ]; then
			echo -ne ""
		elif [ ${perc} -le "100" ]; then
			echo -ne "${normal}BAT: ${green}${perc}"
		elif [ ${perc} -le "50" ]; then
			echo -ne "${normal}BAT: ${yellow}${perc}"
		elif [ ${perc} -le "25" ]; then
			echo -ne "${normal}BAT: ${red}${perc}${time}"
		fi
	fi
}

getCPU() {
	cpu=$(mpstat -P ALL 1 1 | awk '/Average:/ && $2 ~ /all/ {print $3}')
	if [ $(bc <<< "${cpu}<25") == 1 ]; then
		echo -ne "${green}"
	elif [ $(bc <<< "${cpu}<75") == 1 ]; then
		echo -ne "${yellow}"
	else
		echo -ne "${red}$"
	fi
}

getMEM() {
	total=$(free -m | awk '/Mem:/ {print $2}')
	if [ "$(free -V | awk '{print $4}' | cut -d. -f3)" -le 9 ]; then
		mem="$(free -m | awk '/-\/+/ {print $3}')"
	else
		mem="$(bc <<< ${total}-$(free -m | awk '/Mem:/ {print $7}'))"
	fi
	if [ $(bc <<< "${mem}<$(echo ${total}* .25 | bc)") == 1 ]; then
		echo -ne "${green}"
	elif [ $(bc <<< "${mem}<$(echo ${total}* .5 | bc)") == 1 ]; then
		echo -ne "${yellow}"
	else
		echo -ne "${red}"
	fi
}

upd=
getUpdates() {
	if [ "$(checkupdates | wc -l)" -le 0 ]; then
		upd=""
	else
		upd="${red} ${upd} "
	fi
}

getSound() {
	is_muted=$(amixer get Master | awk '/%/ {gsub(/[\[\[]/,""); print $6}' | tail -1)
	cur_device=$(pactl list sinks | awk '/Active Port:/ {print substr($3,15)}' | grep -v "^$")
	if [ ${cur_device} == "headphones" ]; then
		out_device=("  " "  ")
	elif [ ${cur_device} == "lineout" ]; then
		out_device=(" L " " L ")
	else
		out_device=(" 蓼 " " 蓼 ")
	fi

	if [ ${is_muted} == "on" ]; then
		echo -ne "${out_device[0]}-muted"
	else
		echo -ne "${out_device[1]}"
	fi
}

getTime() {
	tme="$(date '+%Y-%m-%d %R')"
	echo -ne "${bluebg}${tme}"
}

while true; do
	#xsetroot -name "$(getBattery) $(getSound) $(getCPU) $(getMEM) $(getTime)"
	xsetroot -name "$(getCPU) $(getMEM) $(getTime)"
done
