#!/bin/bash

sep=" " #""

setBluebg() {
	echo -ne "\x0f"
}

getWeather() {
	infoweather=$(curl -s 'wttr.in/Fredericton?format=%C:%t&period=60')
	IFS=':' read -r condition temperature <<<"$infoweather"
	case ${condition} in
		"Sunny") condition="" ;;
		"Clear") condition="" ;;
               "Cloudy") condition="" ;;
                  "Fog") condition="" ;;
            "HeavyRain") condition="" ;;
         "HeavyShowers") condition="" ;;
            "HeavySnow") condition="" ;;
     "HeavySnowShowers") condition="" ;;
           "Light Rain") condition="" ;;
         "LightShowers") condition="" ;;
           "LightSleet") condition="" ;;
    "LightSleetShowers") condition="" ;;
            "LightSnow") condition="" ;;
     "LightSnowShowers") condition="" ;;
             "Overcast") condition="" ;;
        "Partly cloudy") condition="" ;;
    "ThunderyHeavyRain") condition="" ;;
      "ThunderyShowers") condition="" ;;
  "ThunderySnowShowers") condition="" ;;
	   "VeryCloudy") condition="" ;;
		      *) condition=" ${condition}" ;;
        esac
	echo -ne "${condition} ${temperature}"
}

getBattery() {
	for x in /sys/class/power_supply/BAT?/capacity;
	do
	case "$(cat $x)" in
		100|9[0-9]) echo -ne "" ;;
		8[0-9]|7[0-9]) echo -ne "" ;;
		6[0-9]|5[0-9]) echo -ne "" ;;
		4[0-9]|3[0-9]) echo -ne "" ;;
		*) echo "" ;;
	esac
	done
}

getTime() {
	echo -ne " $(date "+%Y-%m-%d %R")"
}

getNetwork() {
	wireless=$(grep "^s*w" /proc/net/wireless | awk '{ print "", int($3 * 100 / 70) "%" }')
	nettype=$(sed "s/down//;s/up//" /sys/class/net/e*/operstate)
	echo -ne "${nettype}${wireless}"
}

getPlayer() {
	if info=$(cmus-remote -Q 2> /dev/null); then
		status=$(echo "$info" | grep -v "set " | grep -v "tag " | grep "status " | cut -d ' ' -f2)
		if [ "$status" = "playing" ] || [ "$status" = "pause" ] || [ "$status" = "stopped" ];
			title=$(echo "$info" | grep -v "set " | grep " title " | cut -d ' ' -f3-)
			artist=$(echo "$info" | grep -v "set " | grep " artist " | cut -d ' ' -f3-)
			position=$(echo "$info" | grep -v "set " | grep -v "tag " | grep "position " | cut -d ' ' -f2)
			duration=$(echo "$info" | grep -v "set " | grep -v "tag " | grep "duration " | cut -d ' ' -f2)
			if [ "$duration" -ge 0 ]; then
				pos_minutes=$(printf "%02d" $((position / 60)))
				pos_seconds=$(printf "%02d" $((position % 60)))
				dur_minutes=$(printf "%02d" $((duration / 60)))
				dur_seconds=$(printf "%02d" $((duration % 60)))
				info_string="| $pos_minutes:$pos_seconds / $dur_minutes:$dur_seconds"
			fi
			info_string="$artist - $title $info_string"

			if [ "$status" = "playing" ]; then
				echo "#1 $info_string"
			elif [ "$status" = "pause" ]; then
				echo "#2 $info_string"
			elif [ "$status" = "stopped" ]; then
				echo "#3 $info_string"
			else
				echo ""
			fi
		else
			echo ""
		fi
	else
		echo ""
	fi
}

while true; do
	xsetroot -name "$(setBluebg) $getPlayer${sep}$(getWeather)${sep}$(getNetwork)${sep}$(getBattery)${sep}$(getTime)"
	sleep 1m
done

