#!/bin/bash

setBluebg() {
	echo -ne "\x0f"
}
WLAN() {
	echo -ne "$(nmcli device wifi list | sed -rn '1d; /^[*]/ s/ {2,}/;/gp' | awk -F';' 'END{if (NR) {sub(/-.*$/, "", $2); print $2, $7;} else print "-" }')"
}

getWeather() {
	infoweather=$(curl -s 'wttr.in/Fredericton?format=%C:%t&period=60')
	IFS=':' read -r condition temperature <<<"$infoweather"
	case ${condition} in
		"Sunny") condition="" ;;
               "Cloudy") condition="" ;;
                  "Fog") condition="" ;;
            "HeavyRain") condition="" ;;
         "HeavyShowers") condition="" ;;
            "HeavySnow") condition="" ;;
     "HeavySnowShowers") condition="" ;;
            "LightRain") condition="" ;;
         "LightShowers") condition="" ;;
           "LightSleet") condition="" ;;
    "LightSleetShowers") condition="" ;;
            "LightSnow") condition="" ;;
     "LightSnowShowers") condition="" ;;
             "Overcast") condition="" ;;
        "Partly cloudy") condition="" ;;
    "ThunderyHeavyRain") condition="" ;;
      "ThunderyShowers") condition="" ;;
  "ThunderySnowShowers") condition="" ;;
	   "VeryCloudy") condition="" ;;
		      *) condition="" ;;
        esac
	echo -ne "${condition} ${temperature}"
}

getBattery() {
	for x in /sys/class/power_supply/BAT?/capacity;
	do
	case "$(cat $x)" in
		100|9[0-9]) echo -ne "" ;;
		8[0-9]|7[0-9]) echo -ne "" ;;
		6[0-9]|5[0-9]) echo -ne "" ;;
		4[0-9]|3[0-9]) echo -ne "" ;;
		*) echo "" ;;
	esac
	done
}

getTime() {
	echo -ne " $(date "+%Y-%m-%d %R")"
}

getNetwork() {
	wireless=$(grep "^s*w" /proc/net/wireless | awk '{ print " ", int($3 * 100 / 70) "%" }')
	nettype=$(sed "s/down//;s/up//" /sys/class/net/e*/operstate)
	echo -ne "${nettype}${wireless}"
}

while true; do
	xsetroot -name "$(WLAN) | $(setBluebg)$(getWeather) | $(getNetwork) | $(getBattery) | $(getTime)"
	sleep 1m
done

