#!/bin/sh

# needs alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

for i in /tmp/mpvsoc*
do
    [ -e "$i" ] || break
    echo '{ "command": ["set_property", "pause", true] }' | socat - "$i";
done

