#!/bin/bash

config=$HOME/.config/sxhkd/sxhkdrc

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' "$config" | column -t -s $'\t' | rofi -dmenu -markup-rows -lines 32 -i -p "sxhkd hotkey" > /dev/null 2>&1
