#!/bin/sh
! echo "$1" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	dunstify "That doesn't look like a full URL." && exit
RSSFILE="$HOME/.config/newsboat/urls"
if awk '{print $1}' "$RSSFILE" | grep "^$1$" >/dev/null; then
	dunstify "You already have this RSS feed."
else
	echo "$1" >> "$RSSFILE" && dunstify "RSS feed added."
fi
