#!/bin/sh

# Display contents of selection via dunst if running.
# Separate script for i3.

clip=$(xclip -o -selection clipboard)
prim=$(xclip -o -selection primary)

[ -n "$clip" ] && dunstify "Clipboard:" "$clip"
[ -n "$prim" ] && dunstify "Primary:" "$prim"
