#!/bin/sh

git checkout master &&
make clean && rm -f config.h &&
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	git checkout $branch && git push -u origin master
done

