#!/bin/sh
ifinstalled transmission-remote-cli transmission-cli || exit

! pgrep -x transmission-da >/dev/null && transmission-daemon && dunstify "Starting torrent daemon..." && sleep 3 && pkill -RTMIN+7 i3blocks

$TERMINAL -e transmission-remote-cli
