#!/bin/sh

# https://gist.github.com/Blaradox/030f06d165a82583ae817ee954438f2e

# $ volumeControl up
# $ volumeControl down

get_volume() {
	amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

is_mute() {
	amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

send_notification() {
	iconSound="audio-volume-high"
	iconMuted="audio-volume-muted"
	if is_mute ; then
		dunstify -i $iconMuted -r 2593 -u normal " mute"
	else
		volume=$(get_volume)
		bar=$(seq -s "─" 0 "$((volume / 5))" | sed 's/[0-9]//g')
		dunstify -i $iconSound -r 2593 -u normal "    $bar"
	fi
}

case $1 in
	up)
		amixer -D pulse set Master on > /dev/null
		amixer -D pulse sset Master 5%+ > /dev/null
		send_notification
		;;
	down)
		amixer -D pulse set Master on > /dev/null
		amixer -D pulse sset Master 5%- > /dev/null
		send_notification
		;;
	mute)
		amixer -D pulse set Master 1+ toggle > /dev/null
		send_notification
		;;
esac

